server:
  port: 8080

spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true
  datasource:
    druid:
      driver-class-name: ${sky.datasource.driver-class-name}
      url: jdbc:mysql://${sky.datasource.host}:${sky.datasource.port}/${sky.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: ${sky.datasource.username}
      password: ${sky.datasource.password}
      # 启用空闲连接检测，建议开启
      test-while-idle: true
      # 检测空闲连接的间隔时间（毫秒），建议小于minEvictableIdleTimeMillis
      time-between-eviction-runs-millis: 60000
      # 连接在池中最小生存的时间（毫秒），默认30分钟，可根据业务调整
      min-evictable-idle-time-millis: 300000
      # 连接在池中最大生存的时间（毫秒），默认7小时
      max-evictable-idle-time-millis: 900000
      # 获取连接时验证有效性（可选，性能略有损耗但更安全）
      test-on-borrow: false
      test-on-return: false

mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.sky.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true

logging:
  level:
    com:
      sky:
        mapper: debug
        service: info
        controller: info

sky:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: itcast
    # 设置jwt过期时间
    admin-ttl: 7200000
    # 设置前端传递过来的令牌名称
    admin-token-name: token
